### ISSUE TITLE
Template : how to run modules (with pageFunction or via _glob.func in assets/js/helpers/pageloader.js)?

### ISSUE THREAD

**Issue by ccolombijn** [Spectrum-McRaj/Restaurant-Hans#11]
At this moment the template is functional; page items are loaded in the primary nav and pages ( assets/pages) are loaded when one is clicked. When a page is loaded (with pageLoader in assets/js/helpers/pageloader) at this moment pageFunction() is invoked (which determines with a switch case which page is loaded) and calls the main function (like mainReservations() ). Not sure if this is the right way to do this; maybe we don't want to maintain assets/js/helpers/pageloader each time a module/page is added?

**Comment by Tricky1975** [comment]
Christoffel heeft gezegd dat we dit af kunnen sluiten so here goes nothing!
